/// Flutter icons PaymentIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PaymentIcons
///      fonts:
///       - asset: fonts/PaymentIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PaymentIcons {
  PaymentIcons._();

  static const _kFontFam = 'PaymentIcons';
  static const String? _kFontPkg = null;

  static const IconData airtel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bhim = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cod = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gpay = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lazpay = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData master = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onlinebanking = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paytm = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonepe = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupay = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupay_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zest = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
